/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { api_ActionStatusResponse } from './models/api_ActionStatusResponse';
export type { api_AddFriendRequest } from './models/api_AddFriendRequest';
export type { api_AddToQueueBody } from './models/api_AddToQueueBody';
export type { api_AddVerseToTextBoxRequest } from './models/api_AddVerseToTextBoxRequest';
export type { api_AnchorTrainingSessionResponse } from './models/api_AnchorTrainingSessionResponse';
export type { api_BooleanOKResponse } from './models/api_BooleanOKResponse';
export type { api_CreateTagRequest } from './models/api_CreateTagRequest';
export type { api_CreateTextBoxRequest } from './models/api_CreateTextBoxRequest';
export type { api_ErrorResponse } from './models/api_ErrorResponse';
export type { api_FlashcardResponse } from './models/api_FlashcardResponse';
export type { api_FlashcardSessionResponse } from './models/api_FlashcardSessionResponse';
export type { api_generateExerciseRequest } from './models/api_generateExerciseRequest';
export type { api_generateExerciseResponse } from './models/api_generateExerciseResponse';
export type { api_HealthResponse } from './models/api_HealthResponse';
export type { api_impostorWordData } from './models/api_impostorWordData';
export type { api_LookupCatalogVersesRequest } from './models/api_LookupCatalogVersesRequest';
export type { api_PatchUserVerseRequest } from './models/api_PatchUserVerseRequest';
export type { api_ReferenceTrainerResponse } from './models/api_ReferenceTrainerResponse';
export type { api_ReorderQueueBody } from './models/api_ReorderQueueBody';
export type { api_ReplaceLearningVerseRequest } from './models/api_ReplaceLearningVerseRequest';
export type { api_ReplaceLearningVerseResponse } from './models/api_ReplaceLearningVerseResponse';
export type { api_UpdateTagRequest } from './models/api_UpdateTagRequest';
export type { api_UpdateTextBoxRequest } from './models/api_UpdateTextBoxRequest';
export type { api_UpsertUserVerseRequest } from './models/api_UpsertUserVerseRequest';
export type { api_VerseTagMutationRequest } from './models/api_VerseTagMutationRequest';
export type { api_VerseTagsPutRequest } from './models/api_VerseTagsPutRequest';
export type { domain_AddVerseToTextBoxResult } from './models/domain_AddVerseToTextBoxResult';
export type { domain_AnchorTrainingResult } from './models/domain_AnchorTrainingResult';
export type { domain_AnchorTrainingSessionInput } from './models/domain_AnchorTrainingSessionInput';
export type { domain_CatalogVerseDeleteResponse } from './models/domain_CatalogVerseDeleteResponse';
export type { domain_CatalogVerseLookupResponse } from './models/domain_CatalogVerseLookupResponse';
export type { domain_CatalogVersesPageResponse } from './models/domain_CatalogVersesPageResponse';
export type { domain_DashboardCompactFriendActivityEntry } from './models/domain_DashboardCompactFriendActivityEntry';
export type { domain_DashboardCompactFriendsActivityResponse } from './models/domain_DashboardCompactFriendsActivityResponse';
export type { domain_DashboardFriendActivityEntry } from './models/domain_DashboardFriendActivityEntry';
export type { domain_DashboardFriendsActivityResponse } from './models/domain_DashboardFriendsActivityResponse';
export type { domain_DashboardFriendsActivitySummary } from './models/domain_DashboardFriendsActivitySummary';
export type { domain_DeleteUserVerseResult } from './models/domain_DeleteUserVerseResult';
export type { domain_FlashcardSessionInput } from './models/domain_FlashcardSessionInput';
export type { domain_FlashcardSessionResult } from './models/domain_FlashcardSessionResult';
export type { domain_FriendPlayerListItem } from './models/domain_FriendPlayerListItem';
export type { domain_FriendPlayersPageResponse } from './models/domain_FriendPlayersPageResponse';
export type { domain_PlayerProfile } from './models/domain_PlayerProfile';
export type { domain_PublicTextBoxDetailResponse } from './models/domain_PublicTextBoxDetailResponse';
export type { domain_PublicTextBoxesPageResponse } from './models/domain_PublicTextBoxesPageResponse';
export type { domain_PublicTextBoxSummary } from './models/domain_PublicTextBoxSummary';
export type { domain_QueueResponse } from './models/domain_QueueResponse';
export type { domain_QueueVerseItem } from './models/domain_QueueVerseItem';
export type { domain_RemoveTextBoxVerseResult } from './models/domain_RemoveTextBoxVerseResult';
export type { domain_SocialPlayerListItem } from './models/domain_SocialPlayerListItem';
export type { domain_SocialPlayersPageResponse } from './models/domain_SocialPlayersPageResponse';
export type { domain_Tag } from './models/domain_Tag';
export type { domain_TextBoxOwnerPreview } from './models/domain_TextBoxOwnerPreview';
export type { domain_TextBoxStats } from './models/domain_TextBoxStats';
export type { domain_TextBoxSummary } from './models/domain_TextBoxSummary';
export type { domain_TextBoxVerse } from './models/domain_TextBoxVerse';
export type { domain_TextBoxVersesResponse } from './models/domain_TextBoxVersesResponse';
export { domain_TextBoxVisibility } from './models/domain_TextBoxVisibility';
export type { domain_TrainingStepHTTPRequest } from './models/domain_TrainingStepHTTPRequest';
export type { domain_TrainingStepHTTPResponse } from './models/domain_TrainingStepHTTPResponse';
export { domain_Translation } from './models/domain_Translation';
export type { domain_UpsertUserInput } from './models/domain_UpsertUserInput';
export type { domain_User } from './models/domain_User';
export type { domain_UserDashboardStats } from './models/domain_UserDashboardStats';
export type { domain_UserLeaderboardCurrentUser } from './models/domain_UserLeaderboardCurrentUser';
export type { domain_UserLeaderboardEntry } from './models/domain_UserLeaderboardEntry';
export type { domain_UserLeaderboardResponse } from './models/domain_UserLeaderboardResponse';
export type { domain_UserVerse } from './models/domain_UserVerse';
export type { domain_UserVersesPageResponse } from './models/domain_UserVersesPageResponse';
export type { domain_UserWithVerses } from './models/domain_UserWithVerses';
export type { domain_Verse } from './models/domain_Verse';
export { domain_VerseAction } from './models/domain_VerseAction';
export type { domain_VerseAdminSummary } from './models/domain_VerseAdminSummary';
export { domain_VerseDifficultyLevel } from './models/domain_VerseDifficultyLevel';
export { domain_VerseDisplayStatus } from './models/domain_VerseDisplayStatus';
export type { domain_VerseFlow } from './models/domain_VerseFlow';
export { domain_VerseFlowAvailability } from './models/domain_VerseFlowAvailability';
export { domain_VerseFlowCode } from './models/domain_VerseFlowCode';
export { domain_VerseFlowGroup } from './models/domain_VerseFlowGroup';
export { domain_VerseFlowPhase } from './models/domain_VerseFlowPhase';
export type { domain_VerseListItem } from './models/domain_VerseListItem';
export type { domain_VerseListTag } from './models/domain_VerseListTag';
export type { domain_VersePopularityPreviewUser } from './models/domain_VersePopularityPreviewUser';
export { domain_VersePopularityScope } from './models/domain_VersePopularityScope';
export { domain_VerseStatus } from './models/domain_VerseStatus';
export type { domain_VerseTagLinkResponse } from './models/domain_VerseTagLinkResponse';

export { CatalogService } from './services/CatalogService';
export { ExercisesService } from './services/ExercisesService';
export { HealthService } from './services/HealthService';
export { QueueService } from './services/QueueService';
export { TagsService } from './services/TagsService';
export { TextBoxesService } from './services/TextBoxesService';
export { UsersService } from './services/UsersService';
export { UserVersesService } from './services/UserVersesService';
