/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List feedback */
        get: operations["listFeedback"];
        put?: never;
        /** Create feedback */
        post: operations["createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate-exercise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate an AI-powered exercise
         * @description Uses AI (Gemini/Groq/Grok with fallback) to generate an impostor-word exercise.
         */
        post: operations["generateExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags */
        get: operations["listTags"];
        put?: never;
        /** Create tag */
        post: operations["createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete tag */
        delete: operations["deleteTag"];
        options?: never;
        head?: never;
        /** Update tag title */
        patch: operations["updateTag"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update a user */
        post: operations["upsertUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get users leaderboard */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or refresh a Telegram user */
        post: operations["upsertTelegramUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by Telegram ID */
        get: operations["getUserByTelegramId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List friends */
        get: operations["listFriends"];
        put?: never;
        /** Add a friend */
        post: operations["addFriend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/friends/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get friends activity */
        get: operations["listFriendsActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/friends/{friendTelegramId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a friend */
        delete: operations["removeFriend"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List players */
        get: operations["listPlayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/players/{targetTelegramId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get player profile */
        get: operations["getPlayerProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard statistics */
        get: operations["getUserStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/verse-owners/{externalVerseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List verse owners */
        get: operations["listVerseOwners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/verses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a user's verses */
        get: operations["listUserVerses"];
        put?: never;
        /**
         * Add verse to My verses or update progress
         * @description If no User row exists for telegramId yet, creates a minimal user (same defaults as user upsert) so the verse can be linked. Body must include externalVerseId; other fields are optional.
         */
        post: operations["upsertUserVerse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/verses/reference-trainer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get verses for the reference trainer (anchor session)
         * @description Fetches a pool of verses for the anchor training mode. Returns verse details sorted by mastery level for adaptive training.
         */
        get: operations["getReferenceTrainer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/verses/reference-trainer/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save anchor training session results
         * @description Processes training results and awards XP based on outcomes and verse difficulty.
         */
        post: operations["saveReferenceTrainerSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/verses/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List verses in review stage
         * @description Same selection as GET /api/users/{telegramId}/verses?filter=review; returns a flat array (legacy OpenAPI contract).
         */
        get: operations["listUserVersesReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{telegramId}/verses/{externalVerseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete verse progress */
        delete: operations["deleteUserVerse"];
        options?: never;
        head?: never;
        /** Partially update verse progress */
        patch: operations["patchUserVerse"];
        trace?: never;
    };
    "/api/users/{telegramId}/verses/{externalVerseId}/training-step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply one training rating (server-side progress)
         * @description Computes mastery, repetitions, next review, and next training mode from rating (SSOT).
         */
        post: operations["postUserVerseTrainingStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List catalog verses
         * @description Semantically same as GET /api/users/{telegramId}/verses with filter=catalog; response shape is catalog-only (items + totalCount).
         */
        get: operations["listCatalogVerses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verses/{externalVerseId}/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get verse admin summary */
        get: operations["getVerseAdminSummary"];
        put?: never;
        post?: never;
        /** Delete verse from catalog */
        delete: operations["deleteCatalogVerse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verses/{externalVerseId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List verse tags */
        get: operations["listVerseTags"];
        put?: never;
        /** Attach tag to verse */
        post: operations["attachTagToVerse"];
        /** Remove tag from verse */
        delete: operations["removeTagFromVerse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "bible-memory-db_internal_domain.AnchorTrainingResult": {
            /** @description ExternalVerseID identifies the verse being trained. */
            externalVerseId?: string;
            /** @description ModeId is the training mode used: "reference-choice", "broken-mirror", "impostor-word", etc. */
            modeId?: string;
            /** @description Outcome of the answer: "correct_first", "correct_retry", or "wrong". */
            outcome?: string;
        };
        "bible-memory-db_internal_domain.AnchorTrainingSessionInput": {
            /** @description Results are the individual question results from this session. */
            results?: components["schemas"]["bible-memory-db_internal_domain.AnchorTrainingResult"][];
        };
        "bible-memory-db_internal_domain.CatalogVerseDeleteResponse": {
            deletedExternalVerseId?: string;
            ok?: boolean;
        };
        "bible-memory-db_internal_domain.CatalogVersesPageResponse": {
            items?: components["schemas"]["bible-memory-db_internal_domain.VerseListItem"][];
            totalCount?: number;
        };
        "bible-memory-db_internal_domain.CreateFeedbackInput": {
            telegramId: string;
            text: string;
        };
        "bible-memory-db_internal_domain.DashboardFriendActivityEntry": {
            avatarUrl?: string;
            dailyStreak?: number;
            lastActiveAt?: string;
            masteredVerses?: number;
            name?: string;
            telegramId?: string;
            weeklyRepetitions?: number;
            xp?: number;
        };
        "bible-memory-db_internal_domain.DashboardFriendsActivityResponse": {
            entries?: components["schemas"]["bible-memory-db_internal_domain.DashboardFriendActivityEntry"][];
            generatedAt?: string;
            summary?: components["schemas"]["bible-memory-db_internal_domain.DashboardFriendsActivitySummary"];
        };
        "bible-memory-db_internal_domain.DashboardFriendsActivitySummary": {
            activeLast7Days?: number;
            avgStreakDays?: number;
            avgWeeklyRepetitions?: number;
            avgXp?: number;
            friendsTotal?: number;
        };
        "bible-memory-db_internal_domain.DeleteUserVerseResult": {
            status?: string;
            xp?: number;
            xpDelta?: number;
        };
        "bible-memory-db_internal_domain.Feedback": {
            createdAt?: string;
            id?: string;
            telegramId?: string;
            text?: string;
            updatedAt?: string;
        };
        "bible-memory-db_internal_domain.FeedbackPageResponse": {
            items?: components["schemas"]["bible-memory-db_internal_domain.Feedback"][];
            limit?: number;
            offset?: number;
            total?: number;
        };
        "bible-memory-db_internal_domain.FriendPlayerListItem": {
            avatarUrl?: string;
            isFriend?: boolean;
            name?: string;
            nickname?: string;
            telegramId?: string;
            versesCount?: number;
        };
        "bible-memory-db_internal_domain.FriendPlayersPageResponse": {
            items?: components["schemas"]["bible-memory-db_internal_domain.FriendPlayerListItem"][];
            limit?: number;
            offset?: number;
            total?: number;
        };
        "bible-memory-db_internal_domain.PlayerProfile": {
            avatarUrl?: string;
            createdAt?: string;
            dailyStreak?: number;
            displayName?: string;
            isCurrentUser?: boolean;
            isFriend?: boolean;
            lastActiveAt?: string;
            masteredVerses?: number;
            name?: string;
            nickname?: string;
            telegramId?: string;
            weeklyRepetitions?: number;
            xp?: number;
        };
        "bible-memory-db_internal_domain.SocialPlayerListItem": {
            avatarUrl?: string;
            dailyStreak?: number;
            isFriend?: boolean;
            lastActiveAt?: string;
            masteredVerses?: number;
            name?: string;
            telegramId?: string;
            weeklyRepetitions?: number;
            xp?: number;
        };
        "bible-memory-db_internal_domain.SocialPlayersPageResponse": {
            items?: components["schemas"]["bible-memory-db_internal_domain.SocialPlayerListItem"][];
            limit?: number;
            startWith?: number;
            totalCount?: number;
        };
        "bible-memory-db_internal_domain.Tag": {
            createdAt?: string;
            id?: string;
            slug?: string;
            title?: string;
        };
        "bible-memory-db_internal_domain.TrainingStepHTTPRequest": {
            isLearningVerse?: boolean;
            /** @description "learning" | "review" */
            phase?: string;
            rating?: number;
            trainingModeId?: number;
        };
        "bible-memory-db_internal_domain.TrainingStepHTTPResponse": {
            graduatedToReview?: boolean;
            nextTrainingModeId?: number;
            reviewWasSuccessful?: boolean;
            userVerse?: components["schemas"]["bible-memory-db_internal_domain.UserVerse"];
        };
        /** @enum {string} */
        "bible-memory-db_internal_domain.Translation": "NRT" | "SYNOD" | "RBS2" | "BTI";
        "bible-memory-db_internal_domain.UpsertUserInput": {
            avatarUrl?: string;
            name?: string;
            nickname?: string;
            telegramId: string;
            translation?: components["schemas"]["bible-memory-db_internal_domain.Translation"];
        };
        "bible-memory-db_internal_domain.User": {
            avatarUrl?: string;
            createdAt?: string;
            dailyStreak?: number;
            id?: string;
            name?: string;
            nickname?: string;
            telegramId?: string;
            translation?: components["schemas"]["bible-memory-db_internal_domain.Translation"];
            xp?: number;
        };
        "bible-memory-db_internal_domain.UserDashboardStats": {
            dailyStreak?: number;
            dueReviewVerses?: number;
            learningVerses?: number;
            masteredCount?: number;
            reviewVerses?: number;
            stoppedVerses?: number;
            telegramId?: string;
            versesCount?: number;
            waitingReviewVerses?: number;
            xp?: number;
        };
        "bible-memory-db_internal_domain.UserLeaderboardCurrentUser": {
            inTop?: boolean;
            rank?: number;
            versesCount?: number;
            xp?: number;
        };
        "bible-memory-db_internal_domain.UserLeaderboardEntry": {
            avatarUrl?: string;
            name?: string;
            nickname?: string;
            rank?: number;
            score?: number;
            telegramId?: string;
            versesCount?: number;
            xp?: number;
        };
        "bible-memory-db_internal_domain.UserLeaderboardResponse": {
            currentUser?: components["schemas"]["bible-memory-db_internal_domain.UserLeaderboardCurrentUser"];
            items?: components["schemas"]["bible-memory-db_internal_domain.UserLeaderboardEntry"][];
            totalParticipants?: number;
        };
        "bible-memory-db_internal_domain.UserVerse": {
            createdAt?: string;
            flow?: components["schemas"]["bible-memory-db_internal_domain.VerseFlow"];
            id?: number;
            lastReviewedAt?: string;
            lastTrainingModeId?: number;
            masteryLevel?: number;
            nextReviewAt?: string;
            reference?: string;
            repetitions?: number;
            reviewLapseStreak?: number;
            status?: components["schemas"]["bible-memory-db_internal_domain.VerseStatus"];
            telegramId?: string;
            /** @description Text/Reference подставляются при ответе API (Helloao), не из БД. */
            text?: string;
            updatedAt?: string;
            /** @description Joined */
            verse?: components["schemas"]["bible-memory-db_internal_domain.Verse"];
            verseId?: string;
        };
        "bible-memory-db_internal_domain.UserVersesPageResponse": {
            items?: components["schemas"]["bible-memory-db_internal_domain.VerseListItem"][];
            limit?: number;
            offset?: number;
            total?: number;
            totalCount?: number;
        };
        "bible-memory-db_internal_domain.UserWithVerses": {
            avatarUrl?: string;
            createdAt?: string;
            dailyStreak?: number;
            id?: string;
            name?: string;
            nickname?: string;
            telegramId?: string;
            translation?: components["schemas"]["bible-memory-db_internal_domain.Translation"];
            versesCount?: number;
            xp?: number;
        };
        "bible-memory-db_internal_domain.Verse": {
            createdAt?: string;
            difficultyLetters?: number;
            externalVerseId?: string;
            id?: string;
        };
        /** @enum {string} */
        "bible-memory-db_internal_domain.VerseAction": "add_to_my" | "start_learning" | "train" | "pause" | "resume" | "anchor";
        "bible-memory-db_internal_domain.VerseAdminSummary": {
            canDelete?: boolean;
            externalVerseId?: string;
            tagLinksCount?: number;
            userLinksCount?: number;
        };
        /** @enum {string} */
        "bible-memory-db_internal_domain.VerseDifficultyLevel": "EASY" | "MEDIUM" | "HARD" | "EXPERT";
        /** @enum {string} */
        "bible-memory-db_internal_domain.VerseDisplayStatus": "MY" | "LEARNING" | "STOPPED" | "REVIEW" | "MASTERED" | "CATALOG";
        "bible-memory-db_internal_domain.VerseFlow": {
            allowedActions?: components["schemas"]["bible-memory-db_internal_domain.VerseAction"][];
            availability?: components["schemas"]["bible-memory-db_internal_domain.VerseFlowAvailability"];
            availableAt?: string;
            code?: components["schemas"]["bible-memory-db_internal_domain.VerseFlowCode"];
            group?: components["schemas"]["bible-memory-db_internal_domain.VerseFlowGroup"];
            phase?: components["schemas"]["bible-memory-db_internal_domain.VerseFlowPhase"];
            progressPercent?: number;
            remainingLearnings?: number;
            remainingReviews?: number;
        };
        /** @enum {string} */
        "bible-memory-db_internal_domain.VerseFlowAvailability": "READY" | "WAITING" | "PAUSED" | "NONE";
        /** @enum {string} */
        "bible-memory-db_internal_domain.VerseFlowCode": "CATALOG" | "MY" | "LEARNING" | "REVIEW_DUE" | "REVIEW_WAITING" | "MASTERED" | "PAUSED_LEARNING" | "PAUSED_REVIEW" | "PAUSED_MASTERED";
        /** @enum {string} */
        "bible-memory-db_internal_domain.VerseFlowGroup": "catalog" | "library" | "active" | "paused" | "complete";
        /** @enum {string} */
        "bible-memory-db_internal_domain.VerseFlowPhase": "catalog" | "my" | "learning" | "review" | "mastered";
        "bible-memory-db_internal_domain.VerseListItem": {
            contextPromptReference?: string;
            contextPromptText?: string;
            createdAt?: string;
            difficultyLevel?: components["schemas"]["bible-memory-db_internal_domain.VerseDifficultyLevel"];
            externalVerseId?: string;
            flow?: components["schemas"]["bible-memory-db_internal_domain.VerseFlow"];
            lastReviewedAt?: string;
            lastTrainingModeId?: number;
            masteryLevel?: number;
            nextReviewAt?: string;
            popularityPreviewUsers?: components["schemas"]["bible-memory-db_internal_domain.VersePopularityPreviewUser"][];
            popularityScope?: components["schemas"]["bible-memory-db_internal_domain.VersePopularityScope"];
            popularityValue?: number;
            reference?: string;
            repetitions?: number;
            reviewLapseStreak?: number;
            status?: components["schemas"]["bible-memory-db_internal_domain.VerseDisplayStatus"];
            tags?: components["schemas"]["bible-memory-db_internal_domain.VerseListTag"][];
            text?: string;
            updatedAt?: string;
        };
        "bible-memory-db_internal_domain.VerseListTag": {
            id?: string;
            slug?: string;
            title?: string;
        };
        "bible-memory-db_internal_domain.VersePopularityPreviewUser": {
            avatarUrl?: string;
            name?: string;
            telegramId?: string;
        };
        /** @enum {string} */
        "bible-memory-db_internal_domain.VersePopularityScope": "friends" | "players" | "self";
        /** @enum {string} */
        "bible-memory-db_internal_domain.VerseStatus": "MY" | "LEARNING" | "STOPPED";
        "bible-memory-db_internal_domain.VerseTagLinkResponse": {
            externalVerseId?: string;
            id?: string;
            tagId?: string;
        };
        "internal_api.ActionStatusResponse": {
            status?: string;
        };
        "internal_api.AddFriendRequest": {
            targetTelegramId?: string;
        };
        "internal_api.AnchorTrainingSessionResponse": {
            /** @description NewTotalXP is the user's total XP after this session. */
            newTotalXp?: number;
            /** @description XPAwarded is the amount of XP earned in this session. */
            xpAwarded?: number;
        };
        "internal_api.BooleanOKResponse": {
            ok?: boolean;
        };
        "internal_api.CreateTagRequest": {
            slug?: string;
            title?: string;
        };
        "internal_api.ErrorResponse": {
            error?: string;
        };
        "internal_api.HealthResponse": {
            status?: string;
        };
        "internal_api.PatchUserVerseRequest": {
            lastReviewedAt?: string;
            lastTrainingModeId?: number;
            masteryLevel?: number;
            nextReviewAt?: string;
            repetitions?: number;
            reviewLapseStreak?: number;
            status?: string;
        };
        "internal_api.ReferenceTrainerResponse": {
            /** @description MinRequired is the minimum number of verses recommended for a session. */
            minRequired?: number;
            /** @description TotalCount is the total number of verses available in the pool. */
            totalCount?: number;
            /** @description Verses is the pool of user verses available for training. */
            verses?: components["schemas"]["bible-memory-db_internal_domain.UserVerse"][];
        };
        "internal_api.UpdateTagRequest": {
            title?: string;
        };
        "internal_api.UpsertUserVerseRequest": {
            externalVerseId?: string;
            lastReviewedAt?: string;
            lastTrainingModeId?: number;
            masteryLevel?: number;
            nextReviewAt?: string;
            repetitions?: number;
        };
        "internal_api.VerseTagMutationRequest": {
            tagId?: string;
            tagSlug?: string;
        };
        "internal_api.generateExerciseRequest": {
            mode?: string;
            verseReference?: string;
            verseText?: string;
        };
        "internal_api.generateExerciseResponse": {
            data?: components["schemas"]["internal_api.impostorWordData"];
            mode?: string;
        };
        "internal_api.impostorWordData": {
            changedWord?: string;
            correctWord?: string;
            wordIndex?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description Verse-tag payload */
        "internal_api.VerseTagMutationRequest": {
            content: {
                "application/json": components["schemas"]["internal_api.VerseTagMutationRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFeedback: {
        parameters: {
            query?: {
                /** @description Optional Telegram ID filter */
                telegramId?: string;
                /** @description Max items */
                limit?: number;
                /** @description Pagination offset */
                startWith?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.FeedbackPageResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    createFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Feedback payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["bible-memory-db_internal_domain.CreateFeedbackInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.Feedback"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    generateExercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Exercise generation request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["internal_api.generateExerciseRequest"];
            };
        };
        responses: {
            /** @description Generated exercise */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.generateExerciseResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description All AI providers failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.Tag"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    createTag: {
        parameters: {
            query?: {
                /** @description Admin Telegram ID */
                telegramId?: string;
            };
            header?: {
                /** @description Admin Telegram ID */
                "X-Telegram-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        /** @description Tag payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["internal_api.CreateTagRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.Tag"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    deleteTag: {
        parameters: {
            query: {
                /** @description Admin Telegram ID */
                telegramId: string;
            };
            header?: {
                /** @description Admin Telegram ID */
                "X-Telegram-Id"?: string;
            };
            path: {
                /** @description Tag ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.BooleanOKResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    updateTag: {
        parameters: {
            query?: {
                /** @description Admin Telegram ID */
                telegramId?: string;
            };
            header?: {
                /** @description Admin Telegram ID */
                "X-Telegram-Id"?: string;
            };
            path: {
                /** @description Tag ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description Tag title payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["internal_api.UpdateTagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.Tag"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    upsertUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["bible-memory-db_internal_domain.UpsertUserInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.User"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                /** @description Optional current user Telegram ID */
                telegramId?: string;
                /** @description Max items */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.UserLeaderboardResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    upsertTelegramUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Telegram user payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["bible-memory-db_internal_domain.UpsertUserInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.User"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.User"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    getUserByTelegramId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.UserWithVerses"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    listFriends: {
        parameters: {
            query?: {
                /** @description Search by name or nickname */
                search?: string;
                /** @description Max items */
                limit?: number;
                /** @description Pagination offset */
                startWith?: number;
            };
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.FriendPlayersPageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    addFriend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
            };
            cookie?: never;
        };
        /** @description Friend payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["internal_api.AddFriendRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ActionStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    listFriendsActivity: {
        parameters: {
            query?: {
                /** @description Max items */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.DashboardFriendsActivityResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    removeFriend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
                /** @description Friend Telegram ID */
                friendTelegramId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ActionStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    listPlayers: {
        parameters: {
            query?: {
                /** @description Search by name or nickname */
                search?: string;
                /** @description Max items */
                limit?: number;
                /** @description Pagination offset */
                startWith?: number;
            };
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.FriendPlayersPageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    getPlayerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Viewer Telegram ID */
                telegramId: string;
                /** @description Target Telegram ID */
                targetTelegramId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.PlayerProfile"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    getUserStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.UserDashboardStats"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    listVerseOwners: {
        parameters: {
            query?: {
                /** @description Scope */
                scope?: "friends" | "players";
                /** @description Max items */
                limit?: number;
                /** @description Pagination offset */
                startWith?: number;
            };
            header?: never;
            path: {
                /** @description Viewer Telegram ID */
                telegramId: string;
                /** @description External verse ID */
                externalVerseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.SocialPlayersPageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    listUserVerses: {
        parameters: {
            query?: {
                /** @description Verse status */
                status?: "MY" | "LEARNING" | "STOPPED";
                /** @description Sort field */
                orderBy?: "createdAt" | "updatedAt" | "bible" | "popularity";
                /** @description Sort direction */
                order?: "asc" | "desc";
                /** @description Semantic list filter */
                filter?: "catalog" | "friends" | "my" | "learning" | "review" | "mastered" | "stopped";
                /** @description Bible book number filter */
                bookId?: number;
                /** @description Search in verse text or reference */
                search?: string;
                /** @description Comma-separated tag slugs */
                tagSlugs?: string;
                /** @description Max items */
                limit?: number;
                /** @description Pagination offset */
                startWith?: number;
            };
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.UserVersesPageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    upsertUserVerse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
            };
            cookie?: never;
        };
        /** @description Verse progress payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["internal_api.UpsertUserVerseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.UserVerse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    getReferenceTrainer: {
        parameters: {
            query?: {
                /** @description Max items to return */
                limit?: number;
                /** @description Bible translation */
                translation?: "NRT" | "SYNOD" | "RBS2" | "BTI";
            };
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verse pool with metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ReferenceTrainerResponse"];
                };
            };
            /** @description Invalid telegramId */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    saveReferenceTrainerSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
            };
            cookie?: never;
        };
        /** @description Session results */
        requestBody: {
            content: {
                "application/json": components["schemas"]["bible-memory-db_internal_domain.AnchorTrainingSessionInput"];
            };
        };
        responses: {
            /** @description XP awarded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.AnchorTrainingSessionResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    listUserVersesReview: {
        parameters: {
            query?: {
                /** @description Sort field */
                orderBy?: "createdAt" | "updatedAt";
                /** @description Sort direction */
                order?: "asc" | "desc";
            };
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.VerseListItem"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    deleteUserVerse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
                /** @description External verse ID */
                externalVerseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.DeleteUserVerseResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    patchUserVerse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
                /** @description External verse ID */
                externalVerseId: string;
            };
            cookie?: never;
        };
        /** @description Patch payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["internal_api.PatchUserVerseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.UserVerse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    postUserVerseTrainingStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Telegram ID */
                telegramId: string;
                /** @description External verse ID */
                externalVerseId: string;
            };
            cookie?: never;
        };
        /** @description Training step payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["bible-memory-db_internal_domain.TrainingStepHTTPRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.TrainingStepHTTPResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    listCatalogVerses: {
        parameters: {
            query?: {
                /** @description Optional current user Telegram ID */
                telegramId?: string;
                /** @description Bible translation */
                translation?: "NRT" | "SYNOD" | "RBS2" | "BTI";
                /** @description Bible book number filter */
                bookId?: number;
                /** @description Comma-separated tag slugs */
                tagSlugs?: string;
                /** @description Sort field */
                orderBy?: string;
                /** @description Sort direction */
                order?: string;
                /** @description Max items */
                limit?: number;
                /** @description Pagination offset */
                startWith?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.CatalogVersesPageResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    getVerseAdminSummary: {
        parameters: {
            query?: {
                /** @description Admin Telegram ID */
                telegramId?: string;
            };
            header?: {
                /** @description Admin Telegram ID */
                "X-Telegram-Id"?: string;
            };
            path: {
                /** @description External verse ID */
                externalVerseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.VerseAdminSummary"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    deleteCatalogVerse: {
        parameters: {
            query?: {
                /** @description Admin Telegram ID */
                telegramId?: string;
            };
            header?: {
                /** @description Admin Telegram ID */
                "X-Telegram-Id"?: string;
            };
            path: {
                /** @description External verse ID */
                externalVerseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.CatalogVerseDeleteResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    listVerseTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description External verse ID */
                externalVerseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.Tag"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    attachTagToVerse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description External verse ID */
                externalVerseId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["internal_api.VerseTagMutationRequest"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bible-memory-db_internal_domain.VerseTagLinkResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
    removeTagFromVerse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description External verse ID */
                externalVerseId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["internal_api.VerseTagMutationRequest"];
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.BooleanOKResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["internal_api.ErrorResponse"];
                };
            };
        };
    };
}
