export const TRAINING_STAGE_MASTERY_MAX = 7;
export const REPEAT_THRESHOLD_FOR_MASTERED = 5;
export const TOTAL_REPEATS_AND_STAGE_MASTERY_MAX = REPEAT_THRESHOLD_FOR_MASTERED + TRAINING_STAGE_MASTERY_MAX;