export const TRAINING_STAGE_MASTERY_MAX = 7;
export const REVIEW_REPETITION_INTERVAL_DAYS = [1, 3, 5] as const;
export const REPEAT_THRESHOLD_FOR_MASTERED = REVIEW_REPETITION_INTERVAL_DAYS.length;
export const TOTAL_REPEATS_AND_STAGE_MASTERY_MAX = REPEAT_THRESHOLD_FOR_MASTERED + TRAINING_STAGE_MASTERY_MAX;
