import type { bible_memory_db_internal_domain_UserLeaderboardEntry } from "./bible_memory_db_internal_domain_UserLeaderboardEntry";

export type domain_UserLeaderboardEntry = bible_memory_db_internal_domain_UserLeaderboardEntry;