import type { bible_memory_db_internal_domain_CatalogVersesPageResponse } from "./bible_memory_db_internal_domain_CatalogVersesPageResponse";

export type domain_CatalogVersesPageResponse = bible_memory_db_internal_domain_CatalogVersesPageResponse;