import type { bible_memory_db_internal_domain_TrainingStepHTTPRequest } from "./bible_memory_db_internal_domain_TrainingStepHTTPRequest";

export type domain_TrainingStepHTTPRequest = bible_memory_db_internal_domain_TrainingStepHTTPRequest;